In [61]:
import requests

In [62]:
URL = "https://stephen-king-api.onrender.com/api/books"
response=requests.get(URL)
response

In [63]:
# content type
print(response.headers["Content-Type"])

application/json; charset=utf-8

In [64]:
# converting to json
json_data = response.json()
print(type(json_data["data"]))
if isinstance(json_data["data"], list):
    print(len(json_data["data"]))
    print(type(json_data["data"][0]))
    print(json_data["data"][0])

<class 'list'>
64
<class 'dict'>
{'id': 1, 'Year': 1974, 'Title': 'Carrie', 'handle': 'carrie', 'Publisher': 'Doubleday', 'ISBN': '978-0-385-08695-0', 'Pages': 199, 'Notes': [''], 'created_at': '2023-11-13T23:48:47.848Z', 'villains': [{'name': 'Tina Blake', 'url': 'https://stephen-king-api.onrender.com/api/villain/4'}, {'name': 'Cindi', 'url': 'https://stephen-king-api.onrender.com/api/villain/14'}, {'name': 'Myra Crewes', 'url': 'https://stephen-king-api.onrender.com/api/villain/16'}, {'name': 'Billy deLois', 'url': 'https://stephen-king-api.onrender.com/api/villain/25'}, {'name': 'Kenny Garson', 'url': 'https://stephen-king-api.onrender.com/api/villain/38'}, {'name': 'Mary Lila Grace', 'url': 'https://stephen-king-api.onrender.com/api/villain/44'}, {'name': 'Christine Hargensen', 'url': 'https://stephen-king-api.onrender.com/api/villain/49'}, {'name': 'Vic Mooney', 'url': 'https://stephen-king-api.onrender.com/api/villain/75'}, {'name': 'The Mortimer Snerds', 'url': 'https://stephen-king-api.onrender.com/api/villain/77'}, {'name': 'Billy Nolan', 'url': 'https://stephen-king-api.onrender.com/api/villain/80'}, {'name': 'Elenor Richmond', 'url': 'https://stephen-king-api.onrender.com/api/villain/90'}, {'name': 'Rachel Spies', 'url': 'https://stephen-king-api.onrender.com/api/villain/94'}, {'name': 'Jackie Talbot', 'url': 'https://stephen-king-api.onrender.com/api/villain/99'}, {'name': 'Donna and Mary Lila Grace Thibodeau', 'url': 'https://stephen-king-api.onrender.com/api/villain/102'}, {'name': 'Jessica Upshaw', 'url': 'https://stephen-king-api.onrender.com/api/villain/108'}, {'name': 'Norma Watson', 'url': 'https://stephen-king-api.onrender.com/api/villain/109'}, {'name': 'Margaret White', 'url': 'https://stephen-king-api.onrender.com/api/villain/113'}]}

In [65]:
df = pd.json_normalize(json_data["data"])

In [66]:
df

,id,Year,Title,handle,Publisher,ISBN,Pages,Notes,created_at,villains
0,1,1974,Carrie,carrie,Doubleday,978-0-385-08695-0,199,[],2023-11-13T23:48:47.848Z,"[{'name': 'Tina Blake', 'url': 'https://stephe..."
1,2,1975,Salem's Lot,salem-s-lot,Doubleday,978-0-385-00751-1,439,"[Nominee, World Fantasy Award, 1976[2]]",2023-11-13T23:48:48.098Z,"[{'name': 'Kurt Barlow', 'url': 'https://steph..."
2,3,1977,The Shining,the-shining,Doubleday,978-0-385-12167-5,447,"[Runner-up (4th place), Locus Award for Best F...",2023-11-13T23:48:48.219Z,"[{'name': 'Horace M. Derwent', 'url': 'https:/..."
3,4,1977,Rage,rage,Signet Books,978-0-451-07645-8,211,[Published under pseudonym Richard Bachman],2023-11-13T23:48:48.339Z,[]
4,5,1978,The Stand,the-stand,Doubleday,978-0-385-12168-2,823,"[Nominee, World Fantasy Award, 1979, Runner-up...",2023-11-13T23:48:48.477Z,"[{'name': 'Donald Merwin Elbert', 'url': 'http..."
...,...,...,...,...,...,...,...,...,...,...
59,60,2018,Elevation,elevation,Scribner,978-1-98210-231-9,144,[],2023-11-13T23:48:55.291Z,[]
60,61,2019,The Institute,the-institute,Scribner,978-1-98211-056-7,576,"[Nominee, British Fantasy Award's August Derle...",2023-11-13T23:48:55.457Z,"[{'name': 'Gladys Hickson', 'url': 'https://st..."
61,62,2021,Later,later,Hard Case Crime,978-1-78909-649-1,256,[],2023-11-13T23:48:55.579Z,[]
62,63,2021,Billy Summers,billy-summers,Scribner,978-1-982-17361-6,528,[],2023-11-13T23:48:55.753Z,[]
63,72,1979,The Roopak Zone,the-roopak-zone,Viking Press,978-0-670-26069697-5,428,"[Runner-up (2nd place), Locus Award for Best F...",2026-06-26T18:20:32.285Z,[]

In [67]:
print(df.columns)
df.head()

Index(['id', 'Year', 'Title', 'handle', 'Publisher', 'ISBN', 'Pages', 'Notes',
       'created_at', 'villains'],
      dtype='object')

,id,Year,Title,handle,Publisher,ISBN,Pages,Notes,created_at,villains
0,1,1974,Carrie,carrie,Doubleday,978-0-385-08695-0,199,[],2023-11-13T23:48:47.848Z,"[{'name': 'Tina Blake', 'url': 'https://stephe..."
1,2,1975,Salem's Lot,salem-s-lot,Doubleday,978-0-385-00751-1,439,"[Nominee, World Fantasy Award, 1976[2]]",2023-11-13T23:48:48.098Z,"[{'name': 'Kurt Barlow', 'url': 'https://steph..."
2,3,1977,The Shining,the-shining,Doubleday,978-0-385-12167-5,447,"[Runner-up (4th place), Locus Award for Best F...",2023-11-13T23:48:48.219Z,"[{'name': 'Horace M. Derwent', 'url': 'https:/..."
3,4,1977,Rage,rage,Signet Books,978-0-451-07645-8,211,[Published under pseudonym Richard Bachman],2023-11-13T23:48:48.339Z,[]
4,5,1978,The Stand,the-stand,Doubleday,978-0-385-12168-2,823,"[Nominee, World Fantasy Award, 1979, Runner-up...",2023-11-13T23:48:48.477Z,"[{'name': 'Donald Merwin Elbert', 'url': 'http..."