In [1]:
import requests
url="https://dogapi.dog/api/v2/breeds"
res=requests.get(url)

In [2]:
if res.status_code==200:
    print(f"Success. Status Code: {res.status_code}")

Success. Status Code: 200

In [3]:
# res.headers["Content-type"]

#converting to json
json_data=res.json()

In [ ]:
#chek types
print(type(json_data))
print(json_data)

In [7]:
#converting to dataframe
import pandas as pd
df=pd.json_normalize(json_data["data"])

In [18]:
df2=df.copy()

In [17]:
## Inspect the Data
# df.head()
# df.dtypes
# df.shape
# df.columns
# df.isnull().sum()
# df.duplicated().sum()

Index(['id', 'type', 'attributes.name', 'attributes.description',
       'attributes.life.max', 'attributes.life.min',
       'attributes.male_weight.max', 'attributes.male_weight.min',
       'attributes.female_weight.max', 'attributes.female_weight.min',
       'attributes.hypoallergenic', 'relationships.group.data.id',
       'relationships.group.data.type'],
      dtype='object')

In [22]:
#rename columns
df.rename(columns={
    "attributes.name": "name",
    "attributes.life.min": "life_min",
    "attributes.life.max": "life_max",
    "attributes.hypoallergenic": "hypoallergenic"
    "attributes.male_weight.min": "male_weight_min",
    "attributes.male_weight.max": "male_weight_max",
    "attributes.female_weight.min": "female_weight_min",
    "attributes.female_weight.max": "female_weight_max",
    "attributes.hypoallergenic": "hypoallergenic",
    "relationships.group.data.id": "group_id",
    "relationships.group.data.type": "group_type"
},inplace=True)

In [24]:
#create avg life col
df["Avg_life"]=(df["life_min"]+df["life_max"])/2

In [27]:
df.head()
df.nunique()

id                        283
type                        1
name                      283
attributes.description    283
life_max                   10
life_min                    8
male_weight_max            40
male_weight_min            32
female_weight_max          40
female_weight_min          34
hypoallergenic              2
group_id                    9
group_type                  1
Avg_life                   12
dtype: int64

In [28]:
# Drop columns with no analytical value
df.drop(columns=[
    "id",
    "type",
    "group_id",
    "group_type",
    "attributes.description"
], inplace=True)

In [30]:
df.head()

,name,attributes.description,life_max,life_min,male_weight_max,male_weight_min,female_weight_max,female_weight_min,hypoallergenic,Avg_life
0,Affenpinscher,The Affenpinscher is a small and playful breed...,16,14,5,3,5,3,True,15.0
1,Afghan Hound,The Afghan Hound is a large and elegant breed ...,14,12,27,23,25,20,False,13.0
2,Airedale Terrier,The Airedale Terrier is a large and powerful b...,14,12,23,20,20,18,False,13.0
3,Akita,"The Akita is a large, muscular dog breed that ...",12,10,60,35,50,35,False,11.0
4,Alaskan Klee Kai,The Alaskan Klee Kai is a small to medium-size...,15,12,7,6,7,6,False,13.5

In [35]:
df["name"] = df["name"].str.strip()
df["name"] = df["name"].str.lower()
df.sort_values("name")

,name,attributes.description,life_max,life_min,male_weight_max,male_weight_min,female_weight_max,female_weight_min,hypoallergenic,Avg_life
0,affenpinscher,The Affenpinscher is a small and playful breed...,16,14,5,3,5,3,True,15.0
1,afghan hound,The Afghan Hound is a large and elegant breed ...,14,12,27,23,25,20,False,13.0
2,airedale terrier,The Airedale Terrier is a large and powerful b...,14,12,23,20,20,18,False,13.0
3,akita,"The Akita is a large, muscular dog breed that ...",12,10,60,35,50,35,False,11.0
4,alaskan klee kai,The Alaskan Klee Kai is a small to medium-size...,15,12,7,6,7,6,False,13.5
...,...,...,...,...,...,...,...,...,...,...
278,wirehaired vizsla,The Wirehaired Vizsla is a medium-sized breed ...,15,12,30,25,30,25,False,13.5
279,working kelpie,The Working Kelpie is a medium-sized breed of ...,15,12,20,16,20,16,False,13.5
280,xoloitzcuintli,"The Xoloitzcuintli, also known as the Mexican ...",15,12,15,10,15,10,True,13.5
281,yakutian laika,The Yakutian Laika is a medium-sized breed of ...,15,12,30,18,30,18,False,13.5
282,yorkshire terrier,"The Yorkshire Terrier is a small, intelligent ...",15,12,3,2,3,2,False,13.5

In [47]:
df.to_csv("cleaned_data/dog_breeds_cleaned.csv", index=False)

In [46]:
df

,name,life_max,life_min,male_weight_max,male_weight_min,female_weight_max,female_weight_min,hypoallergenic,Avg_life
0,affenpinscher,16,14,5,3,5,3,True,15.0
1,afghan hound,14,12,27,23,25,20,False,13.0
2,airedale terrier,14,12,23,20,20,18,False,13.0
3,akita,12,10,60,35,50,35,False,11.0
4,alaskan klee kai,15,12,7,6,7,6,False,13.5
...,...,...,...,...,...,...,...,...,...
278,wirehaired vizsla,15,12,30,25,30,25,False,13.5
279,working kelpie,15,12,20,16,20,16,False,13.5
280,xoloitzcuintli,15,12,15,10,15,10,True,13.5
281,yakutian laika,15,12,30,18,30,18,False,13.5
282,yorkshire terrier,15,12,3,2,3,2,False,13.5