In [29]:
import pandas as pd
import numpy as np

In [35]:
#DATA
employees = pd.DataFrame({
    "EmployeeID":[101,102,103,104,105,106,107,108,109,110,110],
    "Name":[
        "Ali "," Sara","Ahmed","Ayesha",
        "Bilal","Fatima ","Usman",
        "Areeba","Hamza","Noor","Noor"
    ],
    "Department":[
        "IT","HR","Finance","IT",
        np.nan,"HR","Finance",
        "IT","HR","Finance","Finance"
    ],
    "Age":[25,30,np.nan,29,40,27,35,31,28,45,45],
    "Salary":[50000,60000,70000,np.nan,90000,65000,72000,54000,58000,100000,100000],
    "JoiningDate":[
        "2021-01-10",
        "2020-05-12",
        "2019-07-15",
        "2022-03-18",
        "2018-09-01",
        "2020-11-25",
        "2017-12-30",
        "2023-01-01",
        "2022-08-14",
        "2016-06-06",
        "2016-06-06"
    ],
    "City":[
        " Lahore",
        "Karachi ",
        "Islamabad",
        "lahore",
        "Peshawar",
        "Karachi",
        "Islamabad ",
        "Lahore",
        "Karachi",
        np.nan,
        np.nan
    ],
    "Performance":[
        "Excellent",
        "Good",
        "Average",
        "Excellent",
        "Poor",
        "Good",
        "Average",
        "Excellent",
        "Good",
        "Excellent",
        "Excellent"
    ]
})

In [36]:
# create a copy of the data
employees_copy=employees.copy()

In [32]:
employees.shape
employees.dtypes
employees.nunique()
employees.describe()

       EmployeeID        Age         Salary
count   11.000000  10.000000      10.000000
mean   105.909091  33.500000   71900.000000
std      3.176619   7.397447   18537.949066
min    101.000000  25.000000   50000.000000
25%    103.500000  28.250000   58500.000000
50%    106.000000  30.500000   67500.000000
75%    108.500000  38.750000   85500.000000
max    110.000000  45.000000  100000.000000

In [38]:
#fill missing department ffill
employees["Department"]=employees["Department"].ffill()
#fill missing age with mean
employees["Age"]=employees["Age"].fillna(employees["Age"].mean())
#Fill missing Salary with average salary.
employees["Salary"]=employees["Salary"].fillna(employees["Salary"].mean())
#Fill missing City using ffill.
employees["City"]=employees["City"].ffill()

In [42]:
#dropping duplicates
employees = employees.drop_duplicates(subset=['EmployeeID'])

In [49]:
#Verify duplicates are removed.
employees.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [47]:
#remove leading & trailing spaces from name,city
employees["Name"]=employees["Name"].str.strip()
employees["City"]=employees["City"].str.strip()

C:\Users\user\AppData\Local\Temp\ipykernel_3976\758156858.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  employees["Name"]=employees["Name"].str.strip()
C:\Users\user\AppData\Local\Temp\ipykernel_3976\758156858.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  employees["City"]=employees["City"].str.strip()

In [50]:
employees

,EmployeeID,Name,Department,Age,Salary,JoiningDate,City,Performance
0,101,Ali,IT,25.0,50000.0,2021-01-10,Lahore,Excellent
1,102,Sara,HR,30.0,60000.0,2020-05-12,Karachi,Good
2,103,Ahmed,Finance,33.5,70000.0,2019-07-15,Islamabad,Average
3,104,Ayesha,IT,29.0,71900.0,2022-03-18,lahore,Excellent
4,105,Bilal,IT,40.0,90000.0,2018-09-01,Peshawar,Poor
5,106,Fatima,HR,27.0,65000.0,2020-11-25,Karachi,Good
6,107,Usman,Finance,35.0,72000.0,2017-12-30,Islamabad,Average
7,108,Areeba,IT,31.0,54000.0,2023-01-01,Lahore,Excellent
8,109,Hamza,HR,28.0,58000.0,2022-08-14,Karachi,Good
9,110,Noor,Finance,45.0,100000.0,2016-06-06,Karachi,Excellent

In [55]:
# Select only Name, Salary
employees[["Name","Salary"]]

     Name    Salary
0     Ali   50000.0
1    Sara   60000.0
2   Ahmed   70000.0
3  Ayesha   71900.0
4   Bilal   90000.0
5  Fatima   65000.0
6   Usman   72000.0
7  Areeba   54000.0
8   Hamza   58000.0
9    Noor  100000.0

In [56]:
# Select rows 2–7 using iloc
employees.iloc[2:8]

,EmployeeID,Name,Department,Age,Salary,JoiningDate,City,Performance
2,103,Ahmed,Finance,33.5,70000.0,2019-07-15,Islamabad,Average
3,104,Ayesha,IT,29.0,71900.0,2022-03-18,lahore,Excellent
4,105,Bilal,IT,40.0,90000.0,2018-09-01,Peshawar,Poor
5,106,Fatima,HR,27.0,65000.0,2020-11-25,Karachi,Good
6,107,Usman,Finance,35.0,72000.0,2017-12-30,Islamabad,Average
7,108,Areeba,IT,31.0,54000.0,2023-01-01,Lahore,Excellent

In [57]:
# Select rows 1–5 using loc
employees.loc[1:5]

,EmployeeID,Name,Department,Age,Salary,JoiningDate,City,Performance
1,102,Sara,HR,30.0,60000.0,2020-05-12,Karachi,Good
2,103,Ahmed,Finance,33.5,70000.0,2019-07-15,Islamabad,Average
3,104,Ayesha,IT,29.0,71900.0,2022-03-18,lahore,Excellent
4,105,Bilal,IT,40.0,90000.0,2018-09-01,Peshawar,Poor
5,106,Fatima,HR,27.0,65000.0,2020-11-25,Karachi,Good

In [60]:
# Access EmployeeID of row 3 using iat
employees.iat[3,0]

np.int64(104)

In [61]:
# access Department of row 6 using at
employees.at[6,"Department"]

'Finance'

In [64]:
# Employees with Salary > 60000.

# employees.query("Salary>60000")
#or
employees[employees["Salary"]>60000]

,EmployeeID,Name,Department,Age,Salary,JoiningDate,City,Performance
2,103,Ahmed,Finance,33.5,70000.0,2019-07-15,Islamabad,Average
3,104,Ayesha,IT,29.0,71900.0,2022-03-18,lahore,Excellent
4,105,Bilal,IT,40.0,90000.0,2018-09-01,Peshawar,Poor
5,106,Fatima,HR,27.0,65000.0,2020-11-25,Karachi,Good
6,107,Usman,Finance,35.0,72000.0,2017-12-30,Islamabad,Average
9,110,Noor,Finance,45.0,100000.0,2016-06-06,Karachi,Excellent

In [69]:
# Employees in IT department
# employees[employees["Department"]=="IT"]
#or
employees.query("Department == 'IT'")

,EmployeeID,Name,Department,Age,Salary,JoiningDate,City,Performance
0,101,Ali,IT,25.0,50000.0,2021-01-10,Lahore,Excellent
3,104,Ayesha,IT,29.0,71900.0,2022-03-18,lahore,Excellent
4,105,Bilal,IT,40.0,90000.0,2018-09-01,Peshawar,Poor
7,108,Areeba,IT,31.0,54000.0,2023-01-01,Lahore,Excellent

In [70]:
# Employees in IT and Salary > 55000.
employees[(employees["Department"]=='IT') & (employees["Salary"]>55000)]

,EmployeeID,Name,Department,Age,Salary,JoiningDate,City,Performance
3,104,Ayesha,IT,29.0,71900.0,2022-03-18,lahore,Excellent
4,105,Bilal,IT,40.0,90000.0,2018-09-01,Peshawar,Poor

In [72]:
# Employees older than 30 OR in HR.
employees[(employees["Age"]>30) | (employees["Department"]=="HR")]

,EmployeeID,Name,Department,Age,Salary,JoiningDate,City,Performance
1,102,Sara,HR,30.0,60000.0,2020-05-12,Karachi,Good
2,103,Ahmed,Finance,33.5,70000.0,2019-07-15,Islamabad,Average
4,105,Bilal,IT,40.0,90000.0,2018-09-01,Peshawar,Poor
5,106,Fatima,HR,27.0,65000.0,2020-11-25,Karachi,Good
6,107,Usman,Finance,35.0,72000.0,2017-12-30,Islamabad,Average
7,108,Areeba,IT,31.0,54000.0,2023-01-01,Lahore,Excellent
8,109,Hamza,HR,28.0,58000.0,2022-08-14,Karachi,Good
9,110,Noor,Finance,45.0,100000.0,2016-06-06,Karachi,Excellent

In [75]:
# Use query() to find Salary > 60000 and Department == Finance
employees.query("Salary>60000 & Department=='Finance'")

,EmployeeID,Name,Department,Age,Salary,JoiningDate,City,Performance
2,103,Ahmed,Finance,33.5,70000.0,2019-07-15,Islamabad,Average
6,107,Usman,Finance,35.0,72000.0,2017-12-30,Islamabad,Average
9,110,Noor,Finance,45.0,100000.0,2016-06-06,Karachi,Excellent

In [78]:
# Sort Salary ascending.
employees.sort_values(by='Salary', ascending=True)

,EmployeeID,Name,Department,Age,Salary,JoiningDate,City,Performance
0,101,Ali,IT,25.0,50000.0,2021-01-10,Lahore,Excellent
7,108,Areeba,IT,31.0,54000.0,2023-01-01,Lahore,Excellent
8,109,Hamza,HR,28.0,58000.0,2022-08-14,Karachi,Good
1,102,Sara,HR,30.0,60000.0,2020-05-12,Karachi,Good
5,106,Fatima,HR,27.0,65000.0,2020-11-25,Karachi,Good
2,103,Ahmed,Finance,33.5,70000.0,2019-07-15,Islamabad,Average
3,104,Ayesha,IT,29.0,71900.0,2022-03-18,lahore,Excellent
6,107,Usman,Finance,35.0,72000.0,2017-12-30,Islamabad,Average
4,105,Bilal,IT,40.0,90000.0,2018-09-01,Peshawar,Poor
9,110,Noor,Finance,45.0,100000.0,2016-06-06,Karachi,Excellent

In [79]:
# Sort Salary descending
employees.sort_values(by='Salary', ascending=False)

,EmployeeID,Name,Department,Age,Salary,JoiningDate,City,Performance
9,110,Noor,Finance,45.0,100000.0,2016-06-06,Karachi,Excellent
4,105,Bilal,IT,40.0,90000.0,2018-09-01,Peshawar,Poor
6,107,Usman,Finance,35.0,72000.0,2017-12-30,Islamabad,Average
3,104,Ayesha,IT,29.0,71900.0,2022-03-18,lahore,Excellent
2,103,Ahmed,Finance,33.5,70000.0,2019-07-15,Islamabad,Average
5,106,Fatima,HR,27.0,65000.0,2020-11-25,Karachi,Good
1,102,Sara,HR,30.0,60000.0,2020-05-12,Karachi,Good
8,109,Hamza,HR,28.0,58000.0,2022-08-14,Karachi,Good
7,108,Areeba,IT,31.0,54000.0,2023-01-01,Lahore,Excellent
0,101,Ali,IT,25.0,50000.0,2021-01-10,Lahore,Excellent

In [83]:
#Sort by Department then Salary descending.
employees.sort_values(by=['Department','Salary'],ascending=[True,False])

,EmployeeID,Name,Department,Age,Salary,JoiningDate,City,Performance
9,110,Noor,Finance,45.0,100000.0,2016-06-06,Karachi,Excellent
6,107,Usman,Finance,35.0,72000.0,2017-12-30,Islamabad,Average
2,103,Ahmed,Finance,33.5,70000.0,2019-07-15,Islamabad,Average
5,106,Fatima,HR,27.0,65000.0,2020-11-25,Karachi,Good
1,102,Sara,HR,30.0,60000.0,2020-05-12,Karachi,Good
8,109,Hamza,HR,28.0,58000.0,2022-08-14,Karachi,Good
4,105,Bilal,IT,40.0,90000.0,2018-09-01,Peshawar,Poor
3,104,Ayesha,IT,29.0,71900.0,2022-03-18,lahore,Excellent
7,108,Areeba,IT,31.0,54000.0,2023-01-01,Lahore,Excellent
0,101,Ali,IT,25.0,50000.0,2021-01-10,Lahore,Excellent

In [87]:
# Create Bonus
employees["Bonus"]=employees['Salary']*0.1

C:\Users\user\AppData\Local\Temp\ipykernel_3976\2903539898.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  employees["Bonus"]=employees['Salary']*0.1

In [89]:
employees["Total Salary"]=employees["Salary"]+employees["Bonus"]

C:\Users\user\AppData\Local\Temp\ipykernel_3976\2086379876.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  employees["Total Salary"]=employees["Salary"]+employees["Bonus"]

In [91]:
#Create age groups
# 1. Define the age grouping logic
def categorize_age(age):
    if age < 18:
        return 'Child'
    elif age < 35:
        return 'Young Adult'
    elif age < 55:
        return 'Middle Aged'
    else:
        return 'Senior'

# 2. Apply the function to the 'Age' column
employees['age_group'] = employees['Age'].apply(categorize_age)

C:\Users\user\AppData\Local\Temp\ipykernel_3976\835674587.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  employees['age_group'] = employees['Age'].apply(categorize_age)

In [99]:
#map performance to numbers
performance_dict = {
    'Poor':1,
    'Average':2,
    'Good':3,
    'Excellent':4
}

employees['Performance'] = employees['Performance'].map(performance_dict)

C:\Users\user\AppData\Local\Temp\ipykernel_3976\2042042580.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  employees['Performance'] = employees['Performance'].map(performance_dict)

In [103]:
employees["Department"]=employees["Department"].replace("HR","Human Resources")
employees["Department"]=employees["Department"].replace("IT","Information Tech")

C:\Users\user\AppData\Local\Temp\ipykernel_3976\1652786662.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  employees["Department"]=employees["Department"].replace("HR","Human Resources")
C:\Users\user\AppData\Local\Temp\ipykernel_3976\1652786662.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  employees["Department"]=employees["Department"].replace("IT","Information Tech")

In [106]:
#Find average salary department-wise
employees.groupby("Department")["Salary"].mean()

Department
Finance             80666.666667
Human Resources     61000.000000
Information Tech    66475.000000
Name: Salary, dtype: float64

In [107]:
# Highest salary department-wise
employees.groupby("Department")["Salary"].max()

Department
Finance             100000.0
Human Resources      65000.0
Information Tech     90000.0
Name: Salary, dtype: float64

In [109]:
# Employee count department-wise
employees.groupby("Department")["EmployeeID"].count()

Department
Finance             3
Human Resources     3
Information Tech    4
Name: EmployeeID, dtype: int64

In [111]:
#save to .json
employees.to_json("cleaned_emp_data.json")

In [112]:
employees_copy

,EmployeeID,Name,Department,Age,Salary,JoiningDate,City,Performance
0,101,Ali,IT,25.0,50000.0,2021-01-10,Lahore,Excellent
1,102,Sara,HR,30.0,60000.0,2020-05-12,Karachi,Good
2,103,Ahmed,Finance,NaN,70000.0,2019-07-15,Islamabad,Average
3,104,Ayesha,IT,29.0,NaN,2022-03-18,lahore,Excellent
4,105,Bilal,NaN,40.0,90000.0,2018-09-01,Peshawar,Poor
5,106,Fatima,HR,27.0,65000.0,2020-11-25,Karachi,Good
6,107,Usman,Finance,35.0,72000.0,2017-12-30,Islamabad,Average
7,108,Areeba,IT,31.0,54000.0,2023-01-01,Lahore,Excellent
8,109,Hamza,HR,28.0,58000.0,2022-08-14,Karachi,Good
9,110,Noor,Finance,45.0,100000.0,2016-06-06,NaN,Excellent
10,110,Noor,Finance,45.0,100000.0,2016-06-06,NaN,Excellent